### ISSUE TITLE
Problems with passwords

### ISSUE THREAD

**Issue by granaino** [yadakhov/laradump#4]
Hi, 
thanks for your software. It works great, but I have an issue with the passwords when I generate a table dump, the issue is with special characters, there is a line:

# MySqlDump.php Line: 77
$command = sprintf('mysqldump -u %s -p%s %s -h %s %s --no-create-info --extended-insert --skip-comments > %s', $username, $password, $database, $host, $table, $dataFile);

I think should be: 
$command = sprintf('mysqldump -u %s -p\'%s\' %s -h %s %s --no-create-info --extended-insert --skip-comments > %s', $username, $password, $database, $host, $table, $dataFile);

Thanks for your patience.
Regards.

**Comment by yadakhov** [comment]
I Incorporated the change and it should be in the latest version. Thanks
